push:
    categories:
      - name: Home Alone
        identifier: 'isa_mode'
        actions:
          - identifier: 'HOME_ALONE_MODE_ON'
            title: 'Yes'
            authenticationRequired: yes
            behavior: 'default'
          - identifier: 'HOME_ALONE_MODE_OFF'
            title: 'Nope'
            activationMode: 'background'

      - name: Lights Off When Away
        identifier: 'lights_off_away'
        actions:
          - identifier: 'LIGHTS_OFF'
            title: 'Yes'
            activationMode: 'background'
            destructive: yes
          - identifier: 'LIGHTS_ON'
            title: 'No'
            activationMode: 'background'

      - name: Lights Off When Bedroom Window Open
        identifier: 'lights_off_bedroom'
        actions:
          - identifier: 'LIGHTS_OFF_BEDROOM'
            title: 'Yes'
            activationMode: 'background'
            destructive: yes
          - identifier: 'LIGHTS_ON_BEDROOM'
            title: 'No'
            activationMode: 'background'

      - name: Vacuum Now
        identifier: 'vacuum'
        actions:
          - identifier: 'VACUUM_NOW'
            title: 'Yes'
            authenticationRequired: yes
            behavior: 'default'
          - identifier: 'VACUUM_LATER'
            title: 'Snooze'
            activationMode: 'background'
          - identifier: 'VACUUM_STOP_ASKING'
            title: 'Stop asking'
            activationMode: 'background'
            destructive: yes

      - name: Litterbox Upstairs Cleaning Mode
        identifier: 'cleaning_mode_u_still_on'
        actions:
          - identifier: 'CLEANING_U_DONE'
            title: 'Done'
            # authenticationRequired: yes
            activationMode: 'background'            
            behavior: 'default'
          - identifier: 'CLEANING_U_NOT_DONE'
            title: 'Not done yet'
            activationMode: 'background'
            destructive: yes

      - name: Litterbox Downstairs Cleaning Mode
        identifier: 'cleaning_mode_d_still_on'
        actions:
          - identifier: 'CLEANING_D_DONE'
            title: 'Done'
            # authenticationRequired: yes
            activationMode: 'background'            
            behavior: 'default'
          - identifier: 'CLEANING_D_NOT_DONE'
            title: 'Not done yet'
            activationMode: 'background'
            destructive: yes


      # - name: Alarm Clock
      #   identifier: 'alarm_clock'
      #   actions:
      #     - identifier: 'AWAKE'
      #       title: 'Yes'
      #       destructive: no
      #     - identifier: 'AWAKE_NO'
      #       title: 'No'
      #       destructive: no
      #     - identifier: 'SNOOZE'
      #       title: 'Snooze'
      #       destructive: yes