homeassistant:
  customize:
    script.dafang_up:
      icon: mdi:chevron-up
    script.dafang_down:
      icon: mdi:chevron-down
    script.dafang_left:
      icon: mdi:chevron-left
    script.dafang_right:
      icon: mdi:chevron-right
    switch.dafang_h264_rtsp_server:
      icon: mdi:power-standby
      name: Dafang switch

shell_command:
  dafang_up: !secret dafang_up
  dafang_down: !secret dafang_down
  dafang_left: !secret dafang_left
  dafang_right: !secret dafang_right
  dafang_calibrate: !secret dafang_calibrate
  dafang_all_up: !secret dafang_all_up

camera:
  - platform: generic
    name: Upstairs
    still_image_url: !secret dafang_still_image_url

script:
  dafang_up:
    sequence:
      - service: shell_command.dafang_up
  dafang_down:
    sequence:
      - service: shell_command.dafang_down
  dafang_left:
    sequence:
      - service: shell_command.dafang_left
  dafang_right:
    sequence:
      - service: shell_command.dafang_right
  dafang_calibrate:
    sequence:
      - service: shell_command.dafang_calibrate
  dafang_all_up:
    sequence:
      - service: shell_command.dafang_all_up