homeassistant:
  name: Home
  latitude: !secret lat_coord
  longitude: !secret long_coord
  elevation: 50
  unit_system: metric
  time_zone: !secret time_zone
  customize_glob: !include customglob.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - '/config/www/motion'
config:
hassio:
http:
  api_password: !secret http_password
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 3
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.1
updater:
conversation:
customizer:
  custom_ui: hosted
cloud: !include assistants/cloud.yaml
homekit: !include assistants/homekit.yaml
ios: !include notify/ios_config.yaml

# discovery:

# ########################################
# ###                GUI               ###
# ########################################
lovelace:
  mode: yaml
map:
frontend:
  javascript_version: latest
  themes: !include_dir_named themes

panel_custom: !include panels/panel_custom.yaml
panel_iframe: !include panels/panel_iframe.yaml

custom_updater:
  track:
    - cards
    - components
  # card_urls:
  #   - "https://github.com/kalkih/mini-media-player/blob/master/tracker.json"
  # show_installable: true

# ########################################
# ###              LOGGING             ###
# ########################################

recorder: !include logging/recorder.yaml
history: !include logging/history.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml

########################################
###               HUBS               ###
########################################

zwave:
  usb_path: /dev/ttyACM0
  
deconz:
  host: !secret deconz_ip
  port: !secret deconz_port
  api_key: !secret deconz_api
  
rfxtrx:
  device: /dev/ttyUSB1
  
switch:
  platform: rfxtrx
  automatic_add: False
  signal_repetitions: 5
  devices:
    0b11000417bc0cfe09010f70:
      name: Switch 2
    0b11000226bc0cfe09010f70:
      name: Switch 3
    0b11000317bc0cfe08010f70:
      name: Dimmer switch

      
xiaomi_aqara:
  gateways:
   - mac: !secret xiaomi_mac
     key: !secret xiaomi_key

# ########################################
# ###              ENTITIES             ###
# ########################################
ring:
  username: !secret ring_username
  password: !secret ring_password
  
verisure:
  username: !secret verisure_username
  password: !secret verisure_password
  alarm: 0
  locks: 1
  
media_player: !include entities/media_player.yaml
# scene: !include_dir_merge_list scene
device_tracker: !include entities/device_tracker.yaml
zone: !include_dir_merge_list zones/

# ########################################
# ###             SERVICES             ###
# ########################################
sun:
shopping_list:
notify: !include notify/notify.yaml

python_script:

# mqtt:
#   discovery: true
#   discovery_prefix: homeassistant
#   broker: core-mosquitto
#   username: !secret mqtt_username
#   password: !secret mqtt_password
  
# mqtt_statestream:
#   base_topic: hassio
#   publish_attributes: true
#   publish_timestamps: true
#   include:
#     entities:
#       - counter.litterbox_downstairs_visits
#       - counter.litterbox_upstairs_visits
#       - input_select.washing_machine_status

google:
  client_id: !secret google_id
  client_secret: !secret google_secret

ifttt:
  key: !secret ifttt_key
  
tts:
  - platform: google

ffmpeg:

shell_command:
  lovelace_gen: 'python /config/lovelace-gen.py'
  lovelace_gen_states: !secret lovelace_gen_states