resources:
  - url: /local/card-tools.js?v=297fcc
    type: js
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: https://fonts.googleapis.com/css?family=Roboto+Condensed
    type: css
    
  - url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/swipe-card/swipe-card.min.js
    type: module
  - url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/weather-card.min.js
    type: module
    
  - url: /local/custom-lovelace/alarm_control_panel-card.js?v=0.4.0
    type: js
  - url: /local/custom-lovelace/auto-entities.js?v=3cfd04
    type: js
  - url: /local/custom-lovelace/bignumber-card.js?v=0.0.1
    type: js
  - url: /local/custom-lovelace/button-card.js?v=0.0.3
    type: module
  - url: /local/custom-lovelace/calendar-card.js?v=0.0.8
    type: module
  - url: /local/custom-lovelace/card-modder.js?v=785dd6
    type: js
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=0.2.9
    type: js
  - url: /local/custom-lovelace/dual-gauge-card.js?v=0.2.0
    type: js
  - url: /local/custom-lovelace/entity-attributes-card.js?v=0.1.1
    type: js
  - url: /local/custom-lovelace/fold-entity-row.js?v=6d11d3
    type: js
  - url: /local/custom-lovelace/home-setter.js?v=0.0.1
    type: js
  - url: /local/custom-lovelace/krisinfo-card.js?v=0.0.4
    type: js
  - url: /local/custom-lovelace/layout-card.js?v=a313b7
    type: js
  - url: /local/custom-lovelace/light-card.js?v=0.0.1
    type: js
  - url: /local/custom-lovelace/mini-graph-card-bundle.js?v=0.2.1
    type: module
  - url: /local/custom-lovelace/mini-media-player.js?v=0.6
    type: module
  - url: /local/custom-lovelace/monster-card.js?v=0.2.3
    type: js
  - url: /local/custom-lovelace/plan-coordinates.js?v=0.1.0
    type: js
  - url: /local/custom-lovelace/popup-card.js?v=76720c
    type: js
  - url: /local/custom-lovelace/secondaryinfo-entity-row.js?v.0
    type: js
  - url: /local/custom-lovelace/slider-entity-row.js?v=ba8f50
    type: js
  - url: /local/custom-lovelace/slideshow-card.js?v=0.0.1
    type: js
  - url: /local/custom-lovelace/state-attribute-element.js?v=0.2.0
    type: js
  - url: /local/custom-lovelace/state-element.js?v=0.0.1
    type: js
  - url: /local/custom-lovelace/state-switch.js?v=c806ca
    type: js
  - url: /local/custom-lovelace/text-element.js?v=0.0.2
    type: js
  - url: /local/custom-lovelace/toggle-lock-entity-row.js?v=a57ac1
    type: js
  - url: /local/custom-lovelace/tracker-card.js?v=0.3.0
    type: js
  - url: /local/custom-lovelace/upcoming-media-card.js?v=0.3.4
    type: js
  - url: /local/custom-lovelace/useful-markdown-card.js?v=dfc268
    type: js
  - url: /local/custom-lovelace/username-element.js?v=0.0.1
    type: js
  - url: /local/custom-lovelace/vertical-stack-in-card.js?v=v0.1.0
    type: js
  
title: Home
views:
  - !include lovelace/00_home_view.yaml
  - !include lovelace/10_home_info_view.yaml
  - !include lovelace/20_lights_view.yaml
  - !include lovelace/30_system_info_view.yaml
  - !include lovelace/40_camera_view.yaml
  - !include lovelace/50_cat_view.yaml
  - !include lovelace/60_traffic_view.yaml
  # - !include lovelace/60_floorplan_view.yaml
  # - !include lovelace/70_isa_view.yaml
  - !include lovelace/80_automations_view.yaml
  - !include lovelace/101_dashboard.yaml
  - !include lovelace/minimal_dash.yaml  
  # - !include lovelace/102_alarm_clock.yaml
  # - !include lovelace/103_dashboard_test.yaml
  - !include lovelace/100_settings_view.yaml
  - !include lovelace/krisinfotest.yaml
  # - !include lovelace/everything.yaml

