resources:
- type: module
  url: /local/lovelace/mini-graph-card.js?v=0.0.1
- type: module
  url: /local/lovelace/swipe-card.js?v=0.0.1
- type: js
  url: /local/lovelace/plan-coordinates.js?v=0.1.0
- type: js
  url: /local/lovelace/state-switch.js?v=2b02f2
- type: js
  url: /local/lovelace/upcoming-media-card.js?v=0.3.4
- type: js
  url: /local/lovelace/fold-entity-row.js?v=f28e6e
- type: js
  url: /local/lovelace/slideshow-card.js?v=0.0.1
- type: js
  url: /local/lovelace/weather-card.js?v=0.0.1
- type: js
  url: /local/lovelace/monster-card.js?v=0.2.3
- type: js
  url: /local/lovelace/layout-card.js?v=bd7e5a
- type: js
  url: /local/lovelace/popup-card.js?v=02923e
- type: js
  url: /local/lovelace/light-card.js?v=0.0.1 
- type: js
  url: /local/lovelace/card-modder.js?v=35eb37
- type: js
  url: https://unpkg.com/moment@2.22.2/moment.js
- type: module
  url: /local/lovelace/calendar-card.js?v=0.0.1
- type: js
  url: /local/lovelace/dual-gauge-card.js?v=0.2.0
- type: js
  url: /local/lovelace/kiosk.js?v=0.0.1
- type: module
  url: /local/lovelace/button-card.js?v=0.0.1
- type: js
  url: /local/lovelace/vertical-stack-in-card.js?v=0.1.0
- type: js
  url: /local/lovelace/slider-entity-row.js?v=d6da75
- type: js
  url: /local/lovelace/useful-markdown-card.js?v=dfc268
# - type: js
  # url: /local/lovelace/gauge-card.js?v=0.2.0
- type: js
  url: /local/lovelace/bignumber-card.js?v=0.0.1
- type: js
  url: /local/lovelace/column-card.js?v=c8c80f
- type: js
  url: /local/lovelace/alarm_control_panel-card.js?v=0.4.0
- type: js
  url: /local/lovelace/entity-attributes-card.js?v=0.1.1
- type: js
  url: /local/lovelace/home-setter.js?v=0.0.1
- type: js
  url: /local/lovelace/tracker-card.js?v=0.1.5
- type: js
  url: /local/lovelace/light-slider-element.js?v=0.0.1
- type: js
  url: /local/lovelace/group-card.js?v=0.0.2
- type: js
  url: /local/lovelace/state-element.js?v=0.0.1
- type: js
  url: /local/lovelace/text-element.js?v=0.0.2
- type: js
  url: /local/lovelace/username-element.js?v=0.0.1
- type: js
  url: /local/lovelace/state-attribute-element.js?v=0.2.0
- type: module
  url: /local/lovelace/mini-media-player.js?v=0.5
- type: js
  url: /local/lovelace/toggle-lock-entity-row.js?v=a57ac1
- type: css
  url: https://fonts.googleapis.com/css?family=Roboto+Condensed
- url: /local/card-tools.js?v=0a97d3
  type: js
 
title: Home
views:
  - !include lovelace/00_home_view.yaml
  - !include lovelace/10_home_info_view.yaml
  - !include lovelace/20_lights_view.yaml
  - !include lovelace/30_system_info_view.yaml
  - !include lovelace/40_camera_view.yaml
  - !include lovelace/50_cat_view.yaml
  - !include lovelace/60_traffic_view.yaml
  # - !include lovelace/60_floorplan_view.yaml
  # - !include lovelace/70_isa_view.yaml
  - !include lovelace/80_automations_view.yaml
  # - !include lovelace/101_dashboard.yaml
  # - !include lovelace/102_alarm_clock.yaml
  - !include lovelace/103_dashboard_test.yaml
  - !include lovelace/100_settings_view.yaml
  
  
  
   
  
