resources: !include lovelace/resources.yaml

  
title: Home
views:
  - !include lovelace/00_home_view.yaml
  - !include lovelace/10_home_info_view.yaml
  - !include lovelace/20_lights_view.yaml
  - !include lovelace/30_system_info_view.yaml
  - !include lovelace/40_camera_view.yaml
  - !include lovelace/50_cat_view.yaml
  - !include lovelace/60_traffic_view.yaml
  # - !include lovelace/60_floorplan_view.yaml
  # - !include lovelace/70_isa_view.yaml
  - !include lovelace/80_automations_view.yaml
  # - !include lovelace/101_dashboard.yaml
  - !include lovelace/minimal_dash.yaml  
  # - !include lovelace/102_alarm_clock.yaml
  # - !include lovelace/103_dashboard_test.yaml
  - !include lovelace/100_settings_view.yaml
  - !include lovelace/krisinfotest.yaml
  - !include lovelace/everything.yaml
  




