homeassistant:
  customize:
    alarm_control_panel.house:
      templates:
        hs_color: "if (state === 'disarmed') return [0, 0];
        else if (state === 'triggered') return [0, 85];
        else return [40, 70];"
        icon_color: "if (state === 'disarmed') return [0, 0];
        else if (state === 'triggered') return [0, 85];
        else return [40, 70];"