homeassistant:
  customize:
    alarm_control_panel.house:
      templates:
        hs_color: "if (state === 'disarmed') return [0, 0];
        else if (state === 'triggered') return [0, 85];
        else return [40, 70];"
        icon_color: "if (state === 'disarmed') return [0, 0];
        else if (state === 'triggered') return [0, 85];
        else return [40, 70];"


#   ##########################################################
#   ## CUSTOM ALARM COMPONENT ALARM.YAML
#   ## https://github.com/gazoscalvertos/Hass-Custom-Alarm
#   ## VERSION:  1.0.1
#   ## MODIFIED: 28/03/18
#   ##########################################################
# alarm_control_panel:
#   platform: bwalarm
#   name: House
#   alarm: automation.alarm_triggered
#   warning: automation.alarm_warning
  
#   ##[CODE RELATED]
#   #[REQUIRED] Master Code, should consist of one or more digits ie '6482' ensure your passcode is encapsulated by quotes
#   code: !secret alarm_control_panel_code
#   #[OPTIONAL] Panic Code should consist of one or more digits ie '9876' ensure your passcode is encapsulated by quotes, it needs to be different to your standard alarm code. This enables a special panic mode. This can be used under duress to deactivate the alarm which would appear to the unseeing eye as deactivated however a special attribute [panic_mode] listed under the alarm_control_panel.[identifier] will change to ACTIVE. This status could be used in your automations to send a notification to someone else police/spouse/sibling/neighbour that you are under duress. To deactive this mode arm then disarm your alarm in the usual manner. 
#   panic_code: !secret alarm_control_panel_panic_code
  
#   #[DEFAULT] Grace time in seconds to allow for exit and entry using Away mode
#   pending_time: 60
#   #[DEFAULT] The amount of time the alarm stays triggered before returning to its previous state
#   trigger_time: 300
  
#   ##[STATE RELATED]
#   #[OPTIONAL]
#   armed_perimeter: 
#     ##[OPTIONAL however either an immediate or delayed group must exist] Sensors in this group tigger the alarm immediately 
#     immediate:
#       - sensor.front_door_access_control
#       - binary_sensor.balcony_door
#       - binary_sensor.yard_door
#       # - binary_sensor.door_window_sensor_158d00019f5110 ## Yard Storage
#       - binary_sensor.back_door
#       - binary_sensor.dining_area_window_sensor_sensor
  
#   #[REQUIRED]
#   armed_home: 
#     # #[OPTIONAL] State specific overrides default time above
#     # pending_time: 10
#     # #[OPTIONAL] State specific overrides default time above
#     # trigger_time: 300 
#     ##[OPTIONAL however either an immediate or delayed group must exist] Sensors in this group tigger the alarm immediately 
#     immediate:
#       - sensor.front_door_access_control
#       - binary_sensor.balcony_door
#       - binary_sensor.yard_door

#     # ##[OPTIONAL] Sensors in this group start the clock (pending_time) when tripped before the alarm is triggered 
#     # delayed:
#     #   - binary_sensor.first_floor_motion
  
#   #[REQUIRED]
#   armed_away: 
#     #[OPTIONAL] State specific overrides default time above
#     trigger_time: 600  
#     ##[OPTIONAL however either an immediate or delayed group must exist] Sensors in this group tigger the alarm immediately 
#     immediate:
#       - binary_sensor.passage_pir_sensor
#       - binary_sensor.upstairs_hallway_pir_sensor
#       - binary_sensor.balcony_door
#       - binary_sensor.yard_door
#       # - binary_sensor.door_window_sensor_158d00019f5110 ## Yard Storage
#       - binary_sensor.back_door
#       - binary_sensor.dining_area_window_sensor_sensor
#       - binary_sensor.window_bedroom
#       - binary_sensor.stefans_room_motion
#     ##[OPTIONAL] Sensors in this group start the clock (pending_time) when tripped before the alarm is triggered 
#     delayed:
#       - sensor.front_door_access_control
#       - binary_sensor.yard_door
#     #[OPTIONAL] Use this group to automatically override the warning message on open sensors when arming. (I use this as I have a motion sensor at the front door)
#     override:
#       - binary_sensor.window_bedroom
