script:
  bedroom_tv_on_off:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_53
        data:
          packet:
            - 'JgCMAJaTEzYUNhQ1FBEUERQRFBETEhM2FDYTNhQRFBEUERMSExEUERQ2ExITERQRFBEUERQREzYUERQ2EzYUNhM2FDYUNRQABgCWkxM2FDYUNRQRFBEUERQRExEUNhQ2EzYUERQRFBETERQRFBEUNhMRFBEUERQRFBEUERM2FBEUNRQ2FDYTNhQ2FDUUAA0FAAAAAAAAAAAAAAAA'

automation:
  - alias: 'Notification on window open and lights on'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.window_bedroom
        to: 'on'
        for:
          minutes: 10
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: below_horizon
        - condition: or
          conditions:
            - condition: state
              entity_id: light.bedroom_ceiling_light 
              state: 'on'
            - condition: state
              entity_id: light.bedside_lamp
              state: 'on'
    action:
      - service: notify.ios_isabellas_iphone_x
        data:
          title: 'Bedroom window open'
          message: 'Do you want to turn off lights?'
          data:
            push:
              badge: 0
              category: "lights_off_bedroom"

  - alias: 'Lights off when bedroom window open'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: LIGHTS_OFF_BEDROOM
    action:
      - service: light.turn_off
        entity_id: light.bedroom_ceiling_light, light.bedside_lamp

  - alias: 'Notification on high temp in bedroom'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.temperature_bedroom
        above: 26
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sensor.presence_isa
          state: 'Home'
        - condition: state
          entity_id: binary_sensor.window_bedroom
          state: 'off'
        - condition: time
          after: '12:00:00'
          before: '23:00:00'
    action:
    - service: notify.ios_isabellas_iphone_x
      data:
        title: 'Bedroom temp high'
        message: 'Open the window!'
