homeassistant:
  customize:
    script.dafang_up:
      icon: mdi:chevron-up
    script.dafang_down:
      icon: mdi:chevron-down
    script.dafang_left:
      icon: mdi:chevron-left
    script.dafang_right:
      icon: mdi:chevron-right
    switch.dafang_h264_rtsp_server:
      icon: mdi:power-standby
      name: Dafang switch

# camera:
#   # - platform: ffmpeg
#   #   name: DaFang
#   #   input: !secret dafang_camera_input
#   - platform: mjpeg
#     mjpeg_url: !secret motion_eye_upstairs
#     username: !secret motion_eye_username
#     password: !secret motion_eye_password
#     authentication: "basic"

script:
  dafang_up:
    sequence:
      - service: cover.open_cover
        data:
          entity_id: cover.dafang_move_updown
  dafang_down:
    sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.dafang_move_updown
  dafang_left:
    sequence:
      - service: cover.open_cover
        data:
          entity_id: cover.dafang_move_leftright
  dafang_right:
    sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.dafang_move_leftright