input_boolean:
  sonos:
    name: Sonos

automation:
  - alias: Sonos On
    trigger:
      - platform: state
        entity_id: input_boolean.sonos
        to: 'on'
    action:
      - service: media_player.turn_on
        entity_id: media_player.sonos

  - alias: Sonos Off
    trigger:
      - platform: state
        entity_id: input_boolean.sonos
        to: 'off'
    action:
      - service: media_player.turn_off
        entity_id: media_player.sonos
