history_graph:
  internet_speed_tests:
    name: Internet Speed Tests
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_ping
      - sensor.speedtest_upload 

sensor:
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
    minute: 30
    hour:
      - 6
      - 18