homeassistant:
  customize:
    media_player.shield:
      friendly_name: Chromecast Shield
    media_player.sovrum:
      friendly_name: Chromecast sovrum
    media_player.shield_2:
      friendly_name: Plex Shield
      icon: mdi:plex

sensor:
- platform: plex_recently_added
  token: !secret plex_token
  # server_name: "SHIELD"
  host: !secret plex_host
  port: !secret plex_port
  ssl: false
  ssl_cert: false
  download_images: true
  max: 10

script:
  sonos_say:
    alias: "Sonos TTS script"
    sequence:
     - service: media_player.sonos_snapshot
       data_template:
         entity_id: "{{ sonos_entity }}"
     - service: media_player.sonos_unjoin
       data_template:
         entity_id: "{{ sonos_entity }}"
     - service: media_player.volume_set
       data_template:
         entity_id: "{{ sonos_entity }}"
         volume_level: "{{ volume }}"
     - service: tts.google_say
       data_template:
         entity_id: "{{ sonos_entity }}"
         message: "{{ message }}"
     - delay: "{{ delay }}"
     - service: media_player.sonos_restore
       data_template:
         entity_id: "{{ sonos_entity }}"

automation:
  - alias: '[TTS] Sonos on Media center not on'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: media_player.livingroom_tv
      to: 'on'
    action:
      - delay: '00:02:00'
      - condition: state
        entity_id: media_player.livingroom_movie_system
        state: 'off'
      - condition: state
        entity_id: device_tracker.livingroom_movie_system
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.livingroom_tv
        state: 'home'
      - service: script.sonos_say
        data:
          sonos_entity: media_player.sonos
          volume: 0.2
          message: 'Media system is not turned on'
          delay: '00:00:15'