sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot


automation:
  - alias: 'Hass Started'
    initial_state: 'on'
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: notify.pushbullet_isa
        data:
          title: 'Hass.io Online'
          message: 'Online'

  - alias: 'Hass Ready'
    initial_state: 'on'
    trigger:
      platform: event
      event_type: zwave.network_ready
    action:
      - service: notify.pushbullet_isa
        data:
          title: 'Z-wave network now ready'
          message: 'Home Assistant'
      - delay: 00:05
      - service: homekit.start

  - alias: 'Hass Stopped'
    initial_state: 'on'
    trigger:
      platform: homeassistant
      event: shutdown
    action:
      - service: notify.pushbullet_isa
        data:
          title: 'Hass.io Offline'
          message: 'Offline'

  - alias: Hass New Device Tracked
    trigger:
      platform: event
      event_type: device_tracker_new_device
    action:
      - service: notify.pushbullet_isa
        data_template:
          title: 'New device tracked'
          message: >
            {{trigger.event.data.host_name}} 
            ({{trigger.event.data.entity_id}})

  - alias: Hass Updater
    trigger:
      - platform: state
        entity_id: updater.updater
    action:
      - service: notify.pushbullet_isa
        data_template: 
          title: 'New Home Assistant Release Available'
          message: "Home Assistant  {{ states.updater.updater.state }}  is now available."

  - alias: Snapshot Create Daily at 3 AM
    trigger:
      platform: time
      at: '03:00:00'
    action:
    - service: hassio.snapshot_full
      data_template:
        name: "Automated Snapshot {{ now().strftime('%Y-%m-%d') }}"
    - service: notify.pushbullet_isa
      data_template:
        title: "Creating Snapshot"
        message: "Automated Snapshot {{ now().strftime('%Y-%m-%d') }}"
        
  - alias: Snapshot Upload Daily
    trigger:
      - platform: time
        at: '03:30:00'
    action:
      - service: hassio.addon_stdin
        data:
          addon: "7be23ff5_dropbox_sync"
          input:
            command: "upload"