sensor:
  - platform: scrape
    name: Nacka gator Tweet
    resource: https://twitter.com/Nackagator
    select: ".js-tweet-text-container .tweet-text"

  - platform: waze_travel_time
    name: "Home-Solna Travel Time"
    origin: zone.home
    destination: zone.work_solna
    region: 'EU'
    realtime: true

camera:
- platform: generic
  name: TPL Nacka
  still_image_url: https://api.trafikinfo.trafikverket.se/v1/Images/TrafficFlowCamera_39626472.Jpeg?type=fullsize