weather:
  - platform: darksky
    api_key: !secret darksky_key

sensor:
#   - platform: yr
#     monitored_conditions:
#       # - temperature
#       - symbol
#       - precipitation
# #       - windSpeed
# #       - pressure
# #       - windDirection
# #       - humidity
# #       - fog
# #       - cloudiness
# #       - lowClouds
# #       - mediumClouds
# #       - highClouds
# #       - dewpointTemperature

  - platform: darksky
    api_key: !secret darksky_key
    update_interval:
      minutes: 10
    forecast:
      - 1
    monitored_conditions:
      - summary
      - precip_probability
      - precip_type
      - precip_intensity
      - precip_intensity_max
      - temperature
#   #    - dew_point
      - wind_speed
#   #    - wind_bearing
      - cloud_cover
#       - humidity
#       - icon
      - nearest_storm_distance
      - minutely_summary
#       - daily_summary
#       - hourly_summary
      - apparent_temperature
#       - apparent_temperature_max
#       - apparent_temperature_min
      - temperature_low
      - temperature_high
#   #    - pressure
#       - visibility
#   #    - ozone


  - platform: command_line
    name: "Forecast Stockholm"
    icon: alert-outline
    command: "bash /config/scripts/check-weather-sthlm.sh"
    scan_interval: 180
  - platform: command_line
    name: "Forecast Fiskis"
    icon: alert-outline
    command: "bash /config/scripts/check-weather-fiskis.sh"
    scan_interval: 180
    
camera:
  - platform: generic
    name: "Fisksätra meteogram"
    still_image_url: https://www.yr.no/place/Sweden/Stockholm/Nacka_Kommun/meteogram.svg
    content_type: 'image/svg+xml'
  - platform: generic
    name: "Stockholm meteogram"
    still_image_url: https://www.yr.no/place/Sweden/Stockholm/Stockholm/meteogram.svg
    content_type: 'image/svg+xml'