homeassistant:
  customize:
    # binary_sensor.dining_area_window_sensor_sensor:
    binary_sensor.window_bedroom:
      friendly_name: Bedroom window
      

sensor:
  - platform: template  
    sensors:
      dining_area_window:
        friendly_name: 'Dining area window'
        entity_id: "binary_sensor.dining_area_window_sensor_sensor"
        value_template: '{% if is_state("binary_sensor.dining_area_window_sensor_sensor", "on") %}Open{% elif is_state("binary_sensor.dining_area_window_sensor_sensor", "off")%}Closed{% else %}Unknown{% endif %}'
        icon_template: '{% if is_state("binary_sensor.dining_area_window_sensor_sensor", "on") %}mdi:window-open{% elif is_state("binary_sensor.dining_area_window_sensor_sensor", "off")%}mdi:window-closed{% else %}mdi:comment-question-outline{% endif %}'
      bedroom_window:
        friendly_name: 'Bedroom window'
        entity_id: "binary_sensor.window_bedroom"
        value_template: '{% if is_state("binary_sensor.window_bedroom", "on") %}Open{% elif is_state("binary_sensor.window_bedroom", "off")%}Closed{% else %}Unknown{% endif %}'
        icon_template: '{% if is_state("binary_sensor.window_bedroom", "on") %}mdi:window-open{% elif is_state("binary_sensor.window_bedroom", "off")%}mdi:window-closed{% else %}mdi:comment-question-outline{% endif %}'

alert:
  dining_area_window_open:
    name: Dining area window left open
    done_message: Window closed
    entity_id: binary_sensor.dining_area_window_sensor_sensor
    state: 'on'
    repeat: 15
    can_acknowledge: True
    skip_first: True
    notifiers:
      - ios_isabellas_iphone_x