binary_sensor:
  - platform: ping
    name: "RPi Zero Ping"
    host: 192.168.1.46

sensor:
  - platform: glances
    host: "192.168.1.46"
    name: "RPi Zero"
    version: 3
    resources:
      - 'disk_use_percent'
      - 'memory_use_percent'
      - 'swap_use_percent'
      - 'processor_load'
      - 'cpu_temp'